### creates a custom sec group
#   spins up new EC2 instances
#   waits for ssh to become active on instance


- hosts: localhost

  tasks:
    - name: setting up security/firewall group
      ec2_group:
         name: awssecgrp   # ref aaa
         description: rules allowing traffic on port 22 and 80
         region: ca-central-1a
         rules:
           - proto: tcp
             from_port: 80
             to_port: 80
             cidr_ip: 0.0.0.0/0
           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0
         rules_egress:
           - proto: all
             cidr_ip: 0.0.0.0/0


    - name: provision a EC2 Instance
      ec2:
         key_name: awskeypairone
         region: ca-central-1a
         instance_type: t2.micro
         image: ami-9062d0f4
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
           Name: vsslab
           Owner: naga
         monitoring: no
         vpc_subnet-id: subnet-5678xxxx
         assign_public_ip: yes
         group: awssecgrp # ref aaa 
      register: ec2_out

    - name: wait for ssh to come up
      wait_for: host={{item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: '{{ec2_out_instances}}'





















